/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Data_CONSTANTS_H
#define Data_CONSTANTS_H

#include "Data_types.h"

namespace memanager {

class DataConstants {
 public:
  DataConstants();

};

extern const DataConstants g_Data_constants;

} // namespace

#endif
