/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "Data_constants.h"

namespace memanager {

const DataConstants g_Data_constants;

DataConstants::DataConstants() {
}

} // namespace

