/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "DistBlock_constants.h"

namespace memanager {

const DistBlockConstants g_DistBlock_constants;

DistBlockConstants::DistBlockConstants() {
}

} // namespace

