/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "Table_constants.h"

namespace memanager {

const TableConstants g_Table_constants;

TableConstants::TableConstants() {
}

} // namespace

