/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Table_CONSTANTS_H
#define Table_CONSTANTS_H

#include "Table_types.h"

namespace memanager {

class TableConstants {
 public:
  TableConstants();

};

extern const TableConstants g_Table_constants;

} // namespace

#endif
