/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef trans_table_data_H
#define trans_table_data_H

#include <thrift/TDispatchProcessor.h>
#include "Table_types.h"

namespace memanager {

class trans_table_dataIf {
 public:
  virtual ~trans_table_dataIf() {}
  virtual void trans_table_data(const TTable& tb) = 0;
};

class trans_table_dataIfFactory {
 public:
  typedef trans_table_dataIf Handler;

  virtual ~trans_table_dataIfFactory() {}

  virtual trans_table_dataIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(trans_table_dataIf* /* handler */) = 0;
};

class trans_table_dataIfSingletonFactory : virtual public trans_table_dataIfFactory {
 public:
  trans_table_dataIfSingletonFactory(const boost::shared_ptr<trans_table_dataIf>& iface) : iface_(iface) {}
  virtual ~trans_table_dataIfSingletonFactory() {}

  virtual trans_table_dataIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(trans_table_dataIf* /* handler */) {}

 protected:
  boost::shared_ptr<trans_table_dataIf> iface_;
};

class trans_table_dataNull : virtual public trans_table_dataIf {
 public:
  virtual ~trans_table_dataNull() {}
  void trans_table_data(const TTable& /* tb */) {
    return;
  }
};

typedef struct _trans_table_data_trans_table_data_args__isset {
  _trans_table_data_trans_table_data_args__isset() : tb(false) {}
  bool tb;
} _trans_table_data_trans_table_data_args__isset;

class trans_table_data_trans_table_data_args {
 public:

  trans_table_data_trans_table_data_args() {
  }

  virtual ~trans_table_data_trans_table_data_args() throw() {}

  TTable tb;

  _trans_table_data_trans_table_data_args__isset __isset;

  void __set_tb(const TTable& val) {
    tb = val;
  }

  bool operator == (const trans_table_data_trans_table_data_args & rhs) const
  {
    if (!(tb == rhs.tb))
      return false;
    return true;
  }
  bool operator != (const trans_table_data_trans_table_data_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const trans_table_data_trans_table_data_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class trans_table_data_trans_table_data_pargs {
 public:


  virtual ~trans_table_data_trans_table_data_pargs() throw() {}

  const TTable* tb;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class trans_table_data_trans_table_data_result {
 public:

  trans_table_data_trans_table_data_result() {
  }

  virtual ~trans_table_data_trans_table_data_result() throw() {}


  bool operator == (const trans_table_data_trans_table_data_result & /* rhs */) const
  {
    return true;
  }
  bool operator != (const trans_table_data_trans_table_data_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const trans_table_data_trans_table_data_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class trans_table_data_trans_table_data_presult {
 public:


  virtual ~trans_table_data_trans_table_data_presult() throw() {}


  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class trans_table_dataClient : virtual public trans_table_dataIf {
 public:
  trans_table_dataClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) :
    piprot_(prot),
    poprot_(prot) {
    iprot_ = prot.get();
    oprot_ = prot.get();
  }
  trans_table_dataClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) :
    piprot_(iprot),
    poprot_(oprot) {
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void trans_table_data(const TTable& tb);
  void send_trans_table_data(const TTable& tb);
  void recv_trans_table_data();
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class trans_table_dataProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<trans_table_dataIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (trans_table_dataProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_trans_table_data(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  trans_table_dataProcessor(boost::shared_ptr<trans_table_dataIf> iface) :
    iface_(iface) {
    processMap_["trans_table_data"] = &trans_table_dataProcessor::process_trans_table_data;
  }

  virtual ~trans_table_dataProcessor() {}
};

class trans_table_dataProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  trans_table_dataProcessorFactory(const ::boost::shared_ptr< trans_table_dataIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< trans_table_dataIfFactory > handlerFactory_;
};

class trans_table_dataMultiface : virtual public trans_table_dataIf {
 public:
  trans_table_dataMultiface(std::vector<boost::shared_ptr<trans_table_dataIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~trans_table_dataMultiface() {}
 protected:
  std::vector<boost::shared_ptr<trans_table_dataIf> > ifaces_;
  trans_table_dataMultiface() {}
  void add(boost::shared_ptr<trans_table_dataIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void trans_table_data(const TTable& tb) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->trans_table_data(tb);
    }
    ifaces_[i]->trans_table_data(tb);
  }

};

} // namespace

#endif
