/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef trans_table_row_H
#define trans_table_row_H

#include <thrift/TDispatchProcessor.h>
#include "Table_types.h"

namespace memanager {

class trans_table_rowIf {
 public:
  virtual ~trans_table_rowIf() {}
  virtual void trans_table_row(const TTableRow& tbRow) = 0;
};

class trans_table_rowIfFactory {
 public:
  typedef trans_table_rowIf Handler;

  virtual ~trans_table_rowIfFactory() {}

  virtual trans_table_rowIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(trans_table_rowIf* /* handler */) = 0;
};

class trans_table_rowIfSingletonFactory : virtual public trans_table_rowIfFactory {
 public:
  trans_table_rowIfSingletonFactory(const boost::shared_ptr<trans_table_rowIf>& iface) : iface_(iface) {}
  virtual ~trans_table_rowIfSingletonFactory() {}

  virtual trans_table_rowIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(trans_table_rowIf* /* handler */) {}

 protected:
  boost::shared_ptr<trans_table_rowIf> iface_;
};

class trans_table_rowNull : virtual public trans_table_rowIf {
 public:
  virtual ~trans_table_rowNull() {}
  void trans_table_row(const TTableRow& /* tbRow */) {
    return;
  }
};

typedef struct _trans_table_row_trans_table_row_args__isset {
  _trans_table_row_trans_table_row_args__isset() : tbRow(false) {}
  bool tbRow;
} _trans_table_row_trans_table_row_args__isset;

class trans_table_row_trans_table_row_args {
 public:

  trans_table_row_trans_table_row_args() {
  }

  virtual ~trans_table_row_trans_table_row_args() throw() {}

  TTableRow tbRow;

  _trans_table_row_trans_table_row_args__isset __isset;

  void __set_tbRow(const TTableRow& val) {
    tbRow = val;
  }

  bool operator == (const trans_table_row_trans_table_row_args & rhs) const
  {
    if (!(tbRow == rhs.tbRow))
      return false;
    return true;
  }
  bool operator != (const trans_table_row_trans_table_row_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const trans_table_row_trans_table_row_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class trans_table_row_trans_table_row_pargs {
 public:


  virtual ~trans_table_row_trans_table_row_pargs() throw() {}

  const TTableRow* tbRow;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class trans_table_row_trans_table_row_result {
 public:

  trans_table_row_trans_table_row_result() {
  }

  virtual ~trans_table_row_trans_table_row_result() throw() {}


  bool operator == (const trans_table_row_trans_table_row_result & /* rhs */) const
  {
    return true;
  }
  bool operator != (const trans_table_row_trans_table_row_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const trans_table_row_trans_table_row_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class trans_table_row_trans_table_row_presult {
 public:


  virtual ~trans_table_row_trans_table_row_presult() throw() {}


  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class trans_table_rowClient : virtual public trans_table_rowIf {
 public:
  trans_table_rowClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) :
    piprot_(prot),
    poprot_(prot) {
    iprot_ = prot.get();
    oprot_ = prot.get();
  }
  trans_table_rowClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) :
    piprot_(iprot),
    poprot_(oprot) {
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void trans_table_row(const TTableRow& tbRow);
  void send_trans_table_row(const TTableRow& tbRow);
  void recv_trans_table_row();
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class trans_table_rowProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<trans_table_rowIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (trans_table_rowProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_trans_table_row(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  trans_table_rowProcessor(boost::shared_ptr<trans_table_rowIf> iface) :
    iface_(iface) {
    processMap_["trans_table_row"] = &trans_table_rowProcessor::process_trans_table_row;
  }

  virtual ~trans_table_rowProcessor() {}
};

class trans_table_rowProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  trans_table_rowProcessorFactory(const ::boost::shared_ptr< trans_table_rowIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< trans_table_rowIfFactory > handlerFactory_;
};

class trans_table_rowMultiface : virtual public trans_table_rowIf {
 public:
  trans_table_rowMultiface(std::vector<boost::shared_ptr<trans_table_rowIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~trans_table_rowMultiface() {}
 protected:
  std::vector<boost::shared_ptr<trans_table_rowIf> > ifaces_;
  trans_table_rowMultiface() {}
  void add(boost::shared_ptr<trans_table_rowIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void trans_table_row(const TTableRow& tbRow) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->trans_table_row(tbRow);
    }
    ifaces_[i]->trans_table_row(tbRow);
  }

};

} // namespace

#endif
