/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef TSchema_CONSTANTS_H
#define TSchema_CONSTANTS_H

#include "TSchema_types.h"

namespace memanager {

class TSchemaConstants {
 public:
  TSchemaConstants();

};

extern const TSchemaConstants g_TSchema_constants;

} // namespace

#endif
