/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef DistBlock_CONSTANTS_H
#define DistBlock_CONSTANTS_H

#include "DistBlock_types.h"

namespace memanager {

class DistBlockConstants {
 public:
  DistBlockConstants();

};

extern const DistBlockConstants g_DistBlock_constants;

} // namespace

#endif
